import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { Layout, Button, Checkbox, Form, Input } from "antd";

const Home : NextPage = () => {
    return (
<>
        <Head>
            <title>투어리스트</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Layout>
            <h1>현재 진행 중인 전시관</h1>
            <ul>
                <li>
                    <Link href="/tour/1">
                        2020 개인보호 장구 플랫폼
                    </Link>
                </li>
            </ul>
        </Layout>
</>

    )
}

export default Home
